### ISSUE TITLE
"Official" ChatGPT API support?

### ISSUE THREAD

**Issue by alelordelo** [Yoddikko/yoddChatGPT#1]
Thanks, best ChatGPT app so far!  Core Data support is great! : )

This package implements ChatGPT API support:
https://github.com/alfianlosari/ChatGPTSwift

Could it be used on yoddChatGPT?

Thanks

**Comment by Yoddikko** [comment]
Hi, thanks for the compliments.

What are the differences with the framework I'm using now?

**Comment by alelordelo** [comment]
This one access chatGPT, while the current one you are using access GPT da Vinci

**Comment by Yoddikko** [comment]
Oh got it. In these weeks if I have time I can add this new model then.

**Comment by alelordelo** [comment]
awesome! I will also give it a try

**Comment by Yoddikko** [comment]
Good news, I implemented the new framework!

You can now build it yourself and test it. For now I won't update neither the testflit nor release it as IPA because it could be instable and still need some refactoring.

Overall I think it is working right, for this reason I'm going to close this issue.

**Comment by alelordelo** [comment]
Great! From a quick test, seems to be working!
