### ISSUE TITLE
API Error/The operation could not be completed

### ISSUE THREAD

**Issue by srector13** [Yoddikko/yoddChatGPT#5]
I created 2 different API keys and tried them both, but cannot get a good response from the app. I tried with both OpenAISwift and ChatGPT libraries, as well as all of the OpenAISwift libraries.

I get the following error when using OpenAISwift: The operation couldn’t be completed. (OpenAISwift.OpenAIError error 1.)

I get the following error when using ChatGPT library: API error, check your connection or change model type

**Comment by Yoddikko** [comment]
It happens when:

- Connection is unstable
- You put the app in background while it is genersting the app
- The API key is not pasted correctly
- You have no credit in your OpenAI account. In that case it looks that adding a payment method to your account is enough.

Let me know if anything changes. In the meanwhile check this other GitHub issue to see if you doing the procedure correctly. (wait a sec I'll edit this comment)
